spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: kypizzapp
      password: kypizzapp
      database: kypizzapp
  jpa:
    hibernate:
      ddl-auto: update